version: '3.9'

services:
  api:
    #container_name: go-docker-learn
    build: .
    # ports:
    #   - 8000:8000
    volumes:
      - ./log:/app/log
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on: 
      - api
    ports:
      - 8000:8000
